# Generated by Django 3.2 on 2021-12-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
                ('significado', models.TextField()),
                ('clasificacion', models.CharField(choices=[('choco', 'Chocoano'), ('embera', 'Indigena')], default='choco', max_length=16)),
            ],
        ),
    ]
