# Generated by Django 3.2 on 2022-02-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portavoz', '0003_alter_palabra_clasificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palabra',
            options={'ordering': ['nombre'], 'verbose_name': 'Listado de palabras', 'verbose_name_plural': 'Palabras'},
        ),
        migrations.AlterField(
            model_name='palabra',
            name='clasificacion',
            field=models.CharField(choices=[('afro', 'Afro'), ('Embera Dobida', 'Embera')], default='afro', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='palabra',
            unique_together={('nombre', 'significado', 'clasificacion')},
        ),
    ]
