# Generated by Django 3.2 on 2022-02-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portavoz', '0005_alter_palabra_clasificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='clasificacion',
            field=models.CharField(choices=[('Afro', 'Afro'), ('Embera Dóbida', 'Embera Dóbida')], default='Afro', max_length=16),
        ),
    ]
